In [27]:
#CLUSTERING PROJECT

In [28]:
#Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from scipy import stats
import seaborn as sns
import tslearn
from tslearn.clustering import TimeSeriesKMeans


In [29]:
#importing the dataset
Dataset= pd.read_excel('Production Data.xlsx')
data = Dataset.iloc[7:,[0,-1]].values

In [30]:
# data preparation and visualization
x= pd.DataFrame(data)
x.columns =['datetime','total energy']
x=x[x['total energy']>=1]
x.info()
x.describe()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37513 entries, 0 to 82956
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   datetime      37513 non-null  datetime64[ns]
 1   total energy  37513 non-null  object        
dtypes: datetime64[ns](1), object(1)
memory usage: 879.2+ KB


datetime  total energy
count                 37513       37513.0
unique                37513         342.0
top     2020-09-21 18:30:00           1.0
freq                      1         991.0
first   2018-07-01 07:00:00           NaN
last    2020-11-12 16:00:00           NaN

In [31]:
x = x[x['total energy']<300]
x.info()
x.isna()
x=x.dropna()
x.describe()
x.index = x['datetime']



<class 'pandas.core.frame.DataFrame'>
Int64Index: 37493 entries, 0 to 82956
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   datetime      37493 non-null  datetime64[ns]
 1   total energy  37493 non-null  object        
dtypes: datetime64[ns](1), object(1)
memory usage: 878.7+ KB


In [32]:
x.describe()
x.info()
x.max()
x.head(10)


<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 37493 entries, 2018-07-01 07:00:00 to 2020-11-12 16:00:00
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   datetime      37493 non-null  datetime64[ns]
 1   total energy  37493 non-null  object        
dtypes: datetime64[ns](1), object(1)
memory usage: 878.7+ KB


datetime total energy
datetime                                            
2018-07-01 07:00:00 2018-07-01 07:00:00            8
2018-07-01 07:15:00 2018-07-01 07:15:00           13
2018-07-01 07:30:00 2018-07-01 07:30:00           18
2018-07-01 07:45:00 2018-07-01 07:45:00           18
2018-07-01 08:00:00 2018-07-01 08:00:00           27
2018-07-01 08:15:00 2018-07-01 08:15:00           42
2018-07-01 08:30:00 2018-07-01 08:30:00           51
2018-07-01 08:45:00 2018-07-01 08:45:00           66
2018-07-01 09:00:00 2018-07-01 09:00:00           73
2018-07-01 09:15:00 2018-07-01 09:15:00           87

In [7]:
x= x.iloc[0:,1].apply(pd.to_numeric)

In [26]:
x

8.0

In [43]:
#x_hr = x_min.resample("30min", axis = 0).mean()

In [9]:
df_hr = x.resample('30min',axis = 0).mean()
df_hr.isna()
df_hr=df_hr.dropna()
df_hr.head()

datetime
2018-07-01 07:00:00    10.5
2018-07-01 07:30:00    18.0
2018-07-01 08:00:00    34.5
2018-07-01 08:30:00    58.5
2018-07-01 09:00:00    80.0
Name: total energy, dtype: float64

In [10]:
hr = df_hr

In [11]:
df_day = df_hr.resample('D',axis = 0).std()
df_day.isna()
df_day= df_day.dropna()
df_day.tail(50)
df_day.columns =['datetime','total energy']
df_day = pd.DataFrame(df_day)

In [12]:
df = df_day

In [13]:
from sklearn.preprocessing import StandardScaler
s = StandardScaler()
cols_to_norm = ['total energy']
df = s.fit_transform(df[cols_to_norm])

In [14]:
df

array([[-0.21036946],
       [ 0.3943984 ],
       [-1.49924507],
       [ 0.3727028 ],
       [ 0.47379024],
       [ 0.39035417],
       [ 0.08017183],
       [-0.5398821 ],
       [-0.89043726],
       [ 0.45189606],
       [ 0.23609149],
       [ 0.41754473],
       [ 0.41395414],
       [ 1.31599966],
       [ 0.76101882],
       [ 0.9586138 ],
       [-0.07567933],
       [ 0.28894619],
       [ 0.97923541],
       [ 1.05118589],
       [ 0.56420023],
       [ 1.17018613],
       [ 1.07774933],
       [ 0.72719826],
       [ 0.91950717],
       [ 1.17160142],
       [ 1.10134051],
       [ 0.57759214],
       [ 1.01317308],
       [ 0.77909556],
       [ 0.19922639],
       [ 1.02502229],
       [ 1.00095521],
       [ 0.62426573],
       [-0.77663091],
       [ 0.67947442],
       [ 0.24379164],
       [ 0.45978737],
       [ 0.86173482],
       [ 0.44076947],
       [ 0.21862215],
       [ 0.09439366],
       [ 0.38682601],
       [ 0.34606598],
       [ 0.52095986],
       [ 0

# Silhouette Coefficient
The Silhouette Coefficient is defined for each sample and is composed of two scores(shown in below).
a: The mean distance between a sample and all other points in the same class. This score measure the closeness of points in the same cluster.
b: The mean distance between a sample and all other points in the next nearest cluster. This score measure the distance of points of different
"the score is bounded between -1 for incorrect clustering and +1 for highly dense clustering. Scores around zero indicate overlapping clusters"

# Clustering metrics: Calinski Harabasz score:
The Calinski-Harabasz index also known as the Variance Ratio Criterion, is the ratio of the sum of between-clusters dispersion and of inter-cluster dispersion for all clusters, the higher the score , the better the performances.
equation: 

# Davies-Bouldin Index: 
This index signifies the average ‘similarity’ between clusters, where the similarity is a measure that compares the distance between clusters with the size of the clusters themselves. A lower Davies-Bouldin index relates to a model with better separation between the clusters.
Zero is the lowest possible score. Values closer to zero indicate a better partition.



In [15]:
#from tslearn.clustering import TimeSeriesKMeans
#model = TimeSeriesKMeans(n_clusters=8, metric="dtw", max_iter=10)
#yy = model.fit_transform(df)

#from sklearn.cluster import KMeans
#from sklearn.metrics import silhouette_score
#print(silhouette_score(df, labels, metric='euclidean'))
#from sklearn.metrics import davies_bouldin_score
#from sklearn.metrics import calinski_harabasz_score
#print(davies_bouldin_score(df, labels))
#print(calinski_harabasz_score(df,labels))

In [16]:
df

array([[-0.21036946],
       [ 0.3943984 ],
       [-1.49924507],
       [ 0.3727028 ],
       [ 0.47379024],
       [ 0.39035417],
       [ 0.08017183],
       [-0.5398821 ],
       [-0.89043726],
       [ 0.45189606],
       [ 0.23609149],
       [ 0.41754473],
       [ 0.41395414],
       [ 1.31599966],
       [ 0.76101882],
       [ 0.9586138 ],
       [-0.07567933],
       [ 0.28894619],
       [ 0.97923541],
       [ 1.05118589],
       [ 0.56420023],
       [ 1.17018613],
       [ 1.07774933],
       [ 0.72719826],
       [ 0.91950717],
       [ 1.17160142],
       [ 1.10134051],
       [ 0.57759214],
       [ 1.01317308],
       [ 0.77909556],
       [ 0.19922639],
       [ 1.02502229],
       [ 1.00095521],
       [ 0.62426573],
       [-0.77663091],
       [ 0.67947442],
       [ 0.24379164],
       [ 0.45978737],
       [ 0.86173482],
       [ 0.44076947],
       [ 0.21862215],
       [ 0.09439366],
       [ 0.38682601],
       [ 0.34606598],
       [ 0.52095986],
       [ 0

In [17]:
df_day.to_excel("output.xlsx",
             sheet_name='prod_days')

In [18]:
datadays = pd.ExcelWriter("data_days.xlsx")
df_hr.to_excel(datadays)
datadays.save()

In [19]:
datadays

In [74]:
datamin2 = pd.ExcelWriter("data_mins.xlsx")
x.to_excel(datamin)
datamin2.save()

In [75]:
datamin

In [76]:
df

array([[ 53.84902923],
       [ 67.2727288 ],
       [ 25.2405662 ],
       [ 66.79116352],
       [ 69.03494581],
       [ 67.18296112],
       [ 60.2980143 ],
       [ 46.53501839],
       [ 38.75393819],
       [ 68.54897257],
       [ 63.75887738],
       [ 67.78649518],
       [ 67.70679669],
       [ 87.72900493],
       [ 75.41040051],
       [ 79.79630773],
       [ 56.83867183],
       [ 64.93206411],
       [ 80.25403408],
       [ 81.85107945],
       [ 71.0417266 ],
       [ 84.49246233],
       [ 82.44069352],
       [ 74.65970418],
       [ 78.92827935],
       [ 84.52387659],
       [ 82.96433383],
       [ 71.33897953],
       [ 81.00732992],
       [ 75.81164002],
       [ 62.94060304],
       [ 81.27034043],
       [ 80.73613654],
       [ 72.37496745],
       [ 41.28003525],
       [ 73.60040428],
       [ 63.92979322],
       [ 68.72413174],
       [ 77.64593832],
       [ 68.30200189],
       [ 63.37111997],
       [ 60.61368848],
       [ 67.10464847],
       [ 66

In [77]:
#TRYING 28 CLUSTERS
import tslearn
from tslearn.clustering import TimeSeriesKMeans
model = TimeSeriesKMeans(n_clusters=28, metric="dtw", max_iter=10)
zz= model.fit_predict(df_day)

In [78]:
print((df_day[zz==1]).min())
print((df_day[zz==1]).max())
print(df_day[zz==1])

total energy    14.520101
dtype: float64
total energy    17.313279
dtype: float64
            total energy
datetime                
2018-11-23     15.567573
2018-12-30     16.331174
2019-03-03     16.894347
2019-06-05     15.007245
2019-10-25     14.520101
2019-11-08     15.560471
2019-11-14     15.148628
2019-11-22     15.438567
2020-01-10     15.550380
2020-01-22     16.347382
2020-02-24     15.035728
2020-03-04     16.524441
2020-06-07     17.313279
2020-07-20     15.651099
2020-09-21     16.428098


In [80]:
writer3 = pd.ExcelWriter('28_clusters_by_Stdev.xlsx')
for i in range(1,29):
    (df_day[zz == i-1]).to_excel( writer3,sheet_name='cluster'+str(i))
writer3.save()   

In [82]:
import tslearn
from tslearn.clustering import TimeSeriesKMeans
model = TimeSeriesKMeans(n_clusters=28, metric="dtw", max_iter=10)
qq= model.fit_predict(df_hr)

ValueError: Expected 2D array, got 1D array instead:
array=[10.5 18.  34.5 ... 20.   6.5  1. ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [23]:
#Optimal clusters
import tslearn
from tslearn.clustering import TimeSeriesKMeans
model = TimeSeriesKMeans(n_clusters=28, metric="dtw", max_iter=10)
gg= model.fit_predict(df)

In [24]:
df = s.inverse_transform(df)

In [25]:
print((df[gg== 27]).max())
print((df[gg==27]).min())
len(df[gg== 27])

61.96193144228749
59.42567001229566


41

### print((df[gg== 0]).max())
print((df[gg== 0]).min())
len(df[gg== 0])

In [62]:

a = (df[gg==0])
b = (df[gg==1]) 
c = (df[gg==2])
d = (df[gg==3])
e = (df[gg==4])
f = (df[gg==5])
g = (df[gg==6])
h = (df[gg==7])
i = (df[gg==8])
j= (df[gg==9]) 
k = (df[gg==10])
l = (df[gg==11])
m = (df[gg==12])
n = (df[gg==13])
o = (df[gg==14])
p = (df[gg==15])
q = (df[gg==16])
r = (df[gg==17]) 
s = (df[gg==18])
t = (df[gg==19])
u = (df[gg==20])
v = (df[gg==21])
w = (df[gg==22])
xx = (df[gg==23])
y1 = (df[gg==24])
z = (df[gg==25]) 
a1 = (df[gg==26])
b1= (df[gg==27])




In [63]:
print(a)

[[51.99235211]
 [51.21250875]
 [50.83255469]
 [49.36650634]
 [51.01065532]
 [51.03532838]
 [50.96714984]
 [49.6834015 ]
 [49.44072208]
 [50.87925248]
 [50.97562012]
 [51.0045096 ]
 [50.9364436 ]
 [51.52297957]
 [50.04267119]
 [49.10583808]
 [49.25938329]
 [52.00368577]
 [49.75696888]
 [49.97712139]
 [49.75023451]
 [50.63955963]
 [50.74178916]
 [50.10917696]
 [49.3849349 ]
 [50.5093725 ]
 [49.9961537 ]
 [50.66041066]
 [51.14794329]
 [50.20600419]
 [51.43941614]
 [50.84498255]]


In [64]:
plt.scatter(a[0:,0],a[0:,1],s = 50, c='red',label='Cluster 1')
plt.scatter(b[0:,0],b[0:,1],s = 50, c='blue',label='Cluster 2')
plt.scatter(c[0:,0],c[0:,1],s = 50, c='green',label='Cluster 3')
plt.scatter(d[0:,0],d[0:,1],s = 50, c='yellow',label='Cluster 4')
plt.scatter(e[0:,0],e[0:,1],s = 50, c='gray',label='Cluster 5')
plt.scatter(f[0:,0],f[0:,1],s = 50, c='magenta',label='Cluster 6')
plt.scatter(g[0:,0],g[0:,1],s = 50, c='orange',label='Cluster 7')
plt.scatter(h[0:,0],h[0:,1],s = 50, c='violet',label='Cluster 8')
plt.scatter(i[0:,0],i[0:,1],s = 50, c='bisque',label='Cluster 9')
plt.scatter(j[0:,0],j[0:,1],s = 50, c='tan',label='Cluster 10')
plt.scatter(k[0:,0],k[0:,1],s = 50, c='orangered',label='Cluster 11')
plt.scatter(l[0:,0],l[0:,1],s = 50, c='mocasin',label='Cluster 12')
plt.scatter(m[0:,0],m[0:,1],s = 50, c='black',label='Cluster 13')
plt.scatter(n[0:,0],n[0:,1],s = 50, c='coral',label='Cluster 14')
plt.scatter(o[0:,0],o[0:,1],s = 50, c='brown',label='Cluster 15')
plt.scatter(p[0:,0],p[0:,1],s = 50, c='cyan',label='Cluster 16')
plt.scatter(q[0:,0],q[0:,1],s = 50, c='burlywood',label='Cluster 17')
plt.scatter(r[0:,0],b[0:,1],s = 50, c='seashell',label='Cluster 18')
plt.scatter(s[0:,0],s[0:,1],s = 50, c='navy',label='Cluster 19')
plt.scatter(t[0:,0],t[0:,1],s = 50, c='darkblue',label='Cluster 20')
plt.scatter(u[0:,0],u[0:,1],s = 50, c='',label='Cluster 21')
plt.scatter(v[0:,0],v[0:,1],s = 50, c='hotpink',label='Cluster 22')
plt.scatter(w[0:,0],w[0:,1],s = 50, c='deeppink',label='Cluster 23')
plt.scatter(xx[0:,0],xx[0:,1],s = 50, c='olive',label='Cluster 24')
plt.scatter(y1[0:,0],y1[0:,1],s = 50, c='orchid',label='Cluster 25')
plt.scatter(z[0:,0],z[0:,1],s = 50, c='skyblue',label='Cluster 26')
plt.scatter(a1[0:,0],ai[0:,1],s = 50, c='peru',label='Cluster 27')
plt.scatter(b1[0:,0],b1[0:,1],s = 50, c='mistyrose',label='Cluster 28')

plt.legend()
#plt.(figsize = (20,10))
plt.savefig('fig66.pdf')

IndexError: index 1 is out of bounds for axis 1 with size 1

In [ ]:
print(a)

In [ ]:
print(b)


In [ ]:

np.concatenate((b1.min(),b1.max()))


    

In [ ]:
a = [0.592567403471945, 0.5540136686026598, 0.5388159260143992, 0.537878066114215, 0.5435174294178052, 0.5416705179086604, 0.5474287816420442, 0.5382944481841805, 0.5322274550911543, 0.5253054682637295, 0.5266812721735239, 0.507288037892475, 0.534352110776577, 0.5349537673584522, 0.5082688127779288, 0.5399876616830874, 0.5210784766606671, 0.5365874736989759, 0.533673688242492, 0.5298795771608097, 0.5367653200308707, 0.5362082645498556, 0.5406801373067306, 0.5337914130359563, 0.5335391234190148, 0.5460872852349251, 0.5449233944869065, 0.5442855884334187]

In [ ]:
np.reshape(a,(len(a),1))

In [ ]:
b = (1729.8661378521522, 2251.037990088148, 2865.912051817475, 3157.550287348328, 3852.445950195158, 4663.1386163003035, 4707.297241678141, 5526.254995492849, 6009.89126048468, 6211.705709820585, 6780.005457532854, 6557.452217381617, 8061.87531990594, 7878.5695361652715, 8964.498652073842, 9471.536147240036, 9974.756653725059, 11174.54125978295, 11336.893679391618, 12015.41909253854, 12581.652399665869, 12823.204254883367, 12484.010696247606, 13748.997067316674, 14481.084087183392, 14579.905514413942, 15439.33704286666, 16664.072497001835)

In [ ]:
b

In [ ]:
dav = (0.5630372471881658, 0.5395554633665741, 0.5160922879352821, 0.5188602214674598, 0.5191755293685736, 0.48810962750239517, 0.5194383979109868, 0.49129240272877783, 0.5011509517480108, 0.5193064284178616, 0.5042249335709631, 0.5452478046041982, 0.5156363849998736, 0.5070112325266485, 0.5152756346151959, 0.5177663499019384, 0.512329739462513, 0.5020181618887815, 0.4988643209188945, 0.4987508753775015, 0.4737822362510469, 0.515447772853185, 0.5170169076853709, 0.4996587134218269, 0.4877511684343903, 0.5170417007927481, 0.5021503137377881, 0.5099449831897694)

In [ ]:
dav

In [ ]:
sil = (0.592567403471945, 0.5540136686026598, 0.5388159260143992, 0.537878066114215, 0.5435174294178052, 0.5416705179086604, 0.5474287816420442, 0.5382944481841805, 0.5322274550911543, 0.5253054682637295, 0.5266812721735239, 0.507288037892475, 0.534352110776577, 0.5349537673584522, 0.5082688127779288, 0.5399876616830874, 0.5210784766606671, 0.5365874736989759, 0.533673688242492, 0.5298795771608097, 0.5367653200308707, 0.5362082645498556, 0.5406801373067306, 0.5337914130359563, 0.5335391234190148, 0.5460872852349251, 0.5449233944869065, 0.5442855884334187)

In [ ]:
sil